### ISSUE TITLE
UnboundLocalError: local variable 'function' referenced before assignment

### ISSUE THREAD

**Issue by M1ll3rm4n** [Noooste/_abck-deobfuscator#1]
Hi! Really hyped for this tool, thank you for publishing.
I tried installing and running with the provided example, and unfortunately encountered this error:

py abck.py --url https://www.nike.com/m2eXPQu46ZF2_RAoMu7Bi2zVT4M/zuE3rmfh/cCYfZCEC/CR5aAA/sXZA0 --out _abck.js
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Tools\Noooste Deobber\abck.py", line 212, in <module>
    test = Deobfuscate(args.url or args.input, args.output)
  File "C:\Users\Administrator\Desktop\Tools\Noooste Deobber\abck.py", line 29, in __init__
    self.execute()
  File "C:\Users\Administrator\Desktop\Tools\Noooste Deobber\abck.py", line 193, in execute
    self.replace_pQ()
  File "C:\Users\Administrator\Desktop\Tools\Noooste Deobber\abck.py", line 138, in replace_pQ
    self.pQ_vars = self.evaluate_code(self.convert_dict_to_js(self.NQ_vars) + self.convert_dict_to_js(self.tQ_vars) + "return %s;" % ("[" + function[3] + "]"))
UnboundLocalError: local variable 'function' referenced before assignment

**Comment by Noooste** [comment]
Thanks for the report ! I will fix this issue asap.

**Comment by Noooste** [comment]
Issue fixed with update.
